name: appturismo
description: "A new Flutter project."

publish_to: 'none' # Evita publicar en pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  appwrite: ^16.0.0
  get: ^4.6.5
  geolocator: ^10.1.0
  shared_preferences: ^2.5.3
  image_picker: ^1.1.0 # <--- AÃ‘ADIDO: Para seleccionar y tomar fotos
  
  # Solo este paquete para mapas:
  Maps_flutter: ^2.12.1

  flutter_dotenv: ^5.2.1
  http: ^1.4.0
  get_storage: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # ðŸ”½ðŸ”½ðŸ”½ Â¡Â¡Â¡ASEGÃšRATE DE QUE ESTA SECCIÃ“N ESTÃ‰ ASÃ!!! ðŸ”½ðŸ”½ðŸ”½
  assets:
    - .env # AsegÃºrate de que esta lÃ­nea estÃ© aquÃ­ y bien indentada (4 espacios)
  # ðŸ”¼ðŸ”¼ðŸ”¼ Â¡Â¡Â¡FIN DE LA SECCIÃ“N!!! ðŸ”¼ðŸ”¼ðŸ”¼

dependency_overrides:
  flutter_web_auth_2: ^4.1.0
  flutter_web_auth_2_platform_interface: ^4.1.0